from setuptools import setup, find_packages
import os
import platform

# 获取工具文件的路径
def get_tool_paths():
    tool_paths = []
    tools_dir = os.path.join(os.path.dirname(__file__), 'tools')
    if os.path.exists(tools_dir):
        for root, dirs, files in os.walk(tools_dir):
            for file in files:
                # 根据平台选择正确的工具文件
                if platform.system() == 'Windows' and file == 'yt-dlp_win64.exe':
                    tool_paths.append(os.path.join(root, file))
                elif platform.system() == 'Darwin' and file == 'yt-dlp_macos':
                    tool_paths.append(os.path.join(root, file))
                elif not file in ('yt-dlp_win64.exe', 'yt-dlp_macos'):  # 通用文件
                    tool_paths.append(os.path.join(root, file))
    return tool_paths

setup(
    name="VideoLingo",
    version="2.2.3",
    packages=find_packages(),
    include_package_data=True,
    package_data={
        '': get_tool_paths(),
    },
    install_requires=[
        "streamlit>=1.32.0",
        "yt-dlp>=2024.3.10",
        "openai>=1.12.0",
        "pydub>=0.25.1",
        "moviepy>=1.0.3",
        "ffmpeg-python>=0.2.0",
        "python-dotenv>=1.0.1",
        "PyYAML>=6.0.1",
        "requests>=2.31.0",
        "tqdm>=4.66.2",
        "numpy>=1.26.4",
        "pandas>=2.2.1",
        "spacy>=3.7.4",
        "edge-tts>=6.1.9",
        "demucs>=4.0.1",
        "torch>=2.2.1",
        "torchaudio>=2.2.1",
        "transformers>=4.38.2",
        "accelerate>=0.27.2",
        "sentencepiece>=0.2.0",
        "protobuf>=4.25.3",
        "safetensors>=0.4.2",
        "scipy>=1.12.0",
        "soundfile>=0.12.1",
        "librosa>=0.10.1",
        "resampy>=0.4.2",
        "audioread>=3.0.1",
        "sounddevice>=0.4.6",
        "websockets>=12.0",
        "aiohttp>=3.9.3",
        "aiofiles>=23.2.1",
        "python-multipart>=0.0.9",
        "fastapi>=0.110.0",
        "uvicorn>=0.27.1",
        "pydantic>=2.6.3",
        "typing-extensions>=4.10.0",
        "colorama>=0.4.6",
        "rich>=13.7.1",
        "pygments>=2.17.2",
        "markdown>=3.5.2",
        "mdurl>=0.1.2",
        "click>=8.1.7",
        "watchdog>=4.0.0",
        "gitpython>=3.1.42",
        "semver>=3.0.2",
        "packaging>=24.0",
        "platformdirs>=4.2.2",
        "tomli>=2.0.1",
        "tomli-w>=1.0.0",
        "certifi>=2024.2.2",
        "charset-normalizer>=3.3.2",
        "idna>=3.6",
        "urllib3>=2.2.1",
        "blinker>=1.7.0",
        "cachetools>=5.3.3",
        "click-didyoumean>=0.3.0",
        "click-plugins>=1.1.1",
        "click-repl>=0.3.0",
        "cligj>=0.7.2",
        "colorama>=0.4.6",
        "decorator>=5.1.1",
        "execnet>=2.1.1",
        "fiona>=1.9.5",
        "geopandas>=0.14.3",
        "geopy>=2.4.1",
        "h11>=0.14.0",
        "httpcore>=1.0.4",
        "httpx>=0.27.0",
        "iniconfig>=2.0.0",
        "itsdangerous>=2.1.2",
        "Jinja2>=3.1.3",
        "kiwisolver>=1.4.5",
        "lxml>=5.1.0",
        "MarkupSafe>=2.1.5",
        "matplotlib>=3.8.3",
        "mccabe>=0.7.0",
        "more-itertools>=10.2.0",
        "mpmath>=1.3.0",
        "multidict>=6.0.5",
        "mypy-extensions>=1.0.0",
        "networkx>=3.2.1",
        "numpy>=1.26.4",
        "openpyxl>=3.1.2",
        "packaging>=24.0",
        "pandas>=2.2.1",
        "Pillow>=10.2.0",
        "pluggy>=1.4.0",
        "pycparser>=2.21",
        "pyflakes>=3.2.0",
        "pyparsing>=3.1.2",
        "pytest>=8.0.2",
        "pytest-asyncio>=0.23.5",
        "pytest-cov>=4.1.0",
        "pytest-mock>=3.12.0",
        "pytest-timeout>=2.2.0",
        "pytz>=2024.1",
        "PyYAML>=6.0.1",
        "regex>=2023.12.25",
        "requests>=2.31.0",
        "scipy>=1.12.0",
        "setuptools>=69.2.0",
        "six>=1.16.0",
        "sniffio>=1.3.1",
        "soupsieve>=2.5",
        "sympy>=1.12",
        "tqdm>=4.66.2",
        "typing_extensions>=4.10.0",
        "tzdata>=2024.1",
        "urllib3>=2.2.1",
        "validators>=0.22.0",
        "wcwidth>=0.2.13",
        "Werkzeug>=3.0.1",
        "yarl>=1.9.4",
        "zipp>=3.17.0",
    ],
    entry_points={
        'console_scripts': [
            'videolingo=core.main:main',
        ],
    },
    author="VideoLingo Team",
    author_email="your.email@example.com",
    description="A powerful video translation and dubbing tool",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/totang2/VideoLingo",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: End Users/Desktop",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
) 